version: "3.8"
services:
  electoral-system-api:
    build:
      context: ./services/electoral-system-api
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Porta do host : Porta no container
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/electoral_db
    depends_on:
      - postgres

  joystick-api:
    build:
      context: ./services/joystick-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Porta do host : Porta no container
    depends_on:
      - mongodb

  rgbwallet-api:
    build:
      context: ./services/rgbwallet-api
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - mongodb

  secret-santa-api:
    build:
      context: ./services/secret-santa-api
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: electoral_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgres_data:
